// Package server provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package server

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"time"

	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
)

// Defines values for ErrorType.
const (
	ABORTED            ErrorType = "ABORTED"
	ALREADYEXISTS      ErrorType = "ALREADY_EXISTS"
	DEADLINEEXCEEDED   ErrorType = "DEADLINE_EXCEEDED"
	FAILEDPRECONDITION ErrorType = "FAILED_PRECONDITION"
	INTERNAL           ErrorType = "INTERNAL"
	INVALIDARGUMENT    ErrorType = "INVALID_ARGUMENT"
	NOTFOUND           ErrorType = "NOT_FOUND"
	OUTOFRANGE         ErrorType = "OUT_OF_RANGE"
	PERMISSIONDENIED   ErrorType = "PERMISSION_DENIED"
	RESOURCEEXHAUSTED  ErrorType = "RESOURCE_EXHAUSTED"
	UNAUTHENTICATED    ErrorType = "UNAUTHENTICATED"
	UNAVAILABLE        ErrorType = "UNAVAILABLE"
	UNIMPLEMENTED      ErrorType = "UNIMPLEMENTED"
)

// Defines values for PolicyPolicyType.
const (
	GLOBAL PolicyPolicyType = "GLOBAL"
	USER   PolicyPolicyType = "USER"
)

// Error Error response following RFC 7807 Problem Details and AEP-193.
//
// Provides structured error information for API failures.
type Error struct {
	// Detail Human-readable explanation specific to this occurrence of the problem.
	// Should provide actionable information for developers.
	Detail *string `json:"detail,omitempty"`

	// Instance Unique identifier for this specific error occurrence. Useful for
	// tracking and debugging.
	Instance *string `json:"instance,omitempty"`

	// Status HTTP status code
	Status int32 `json:"status"`

	// Title Human-readable summary of the problem type
	Title string `json:"title"`

	// Type URI reference identifying the problem type. This is the canonical
	// error code.
	Type ErrorType `json:"type"`
}

// ErrorType URI reference identifying the problem type. This is the canonical
// error code.
type ErrorType string

// Health defines model for Health.
type Health struct {
	// Path Canonical path of the resource
	Path *string `json:"path,omitempty"`

	// Status Health status
	Status string `json:"status"`
}

// ListPoliciesResponse Response message for listing policies.
//
// Implements AEP-132 List standard method requirements.
type ListPoliciesResponse struct {
	// NextPageToken Token for retrieving the next page of results. If empty or not
	// present, there are no more results.
	//
	// This token is opaque and should not be parsed by clients.
	NextPageToken *string `json:"next_page_token,omitempty"`

	// Policies List of policy resources matching the request criteria
	Policies []Policy `json:"policies"`
}

// Policy Represents an OPA (Open Policy Agent) policy resource.
//
// Policies define authorization rules using Rego code and can be scoped
// to different levels (GLOBAL or USER). They are matched against
// requests using label selectors and evaluated in priority order.
type Policy struct {
	// CreateTime Timestamp when the policy was created. This field is output-only
	// and automatically set by the server.
	//
	// Uses ISO 8601 format with timezone per AEP-140.
	CreateTime *time.Time `json:"create_time,omitempty"`

	// Description Optional detailed description of the policy's purpose and behavior.
	// Supports markdown formatting.
	Description *string `json:"description,omitempty"`

	// DisplayName Human-readable name for the policy. This is typically shown in
	// user interfaces and should be descriptive.
	DisplayName string `json:"display_name"`

	// Enabled Whether the policy is currently active. Disabled policies are not
	// evaluated during authorization decisions.
	Enabled *bool `json:"enabled,omitempty"`

	// Id Unique identifier for the policy. This field is output-only and
	// immutable after creation. The ID can be optionally specified via
	// query parameter on creation; if not provided, the server generates a UUID.
	//
	// Follows AEP-122 resource ID conventions.
	Id *string `json:"id,omitempty"`

	// LabelSelector Key-value pairs used to match this policy against incoming requests.
	// The policy is evaluated only if all labels match the request context.
	// If no label selector is provided, the policy is evaluated for all requests.
	//
	// Common label keys:
	// - environment: production, staging, development
	// - user_id: user identifier
	// - service: service name
	// - region: geographical region
	// - tier: service tier (critical, standard, etc.)
	LabelSelector *map[string]string `json:"label_selector,omitempty"`

	// Path Resource path in the format "policies/{policyId}".
	// This field is output-only and set by the server.
	//
	// Follows AEP-122 resource path conventions.
	Path *string `json:"path,omitempty"`

	// PolicyType Scope of the policy application. This field is immutable after creation.
	//
	// - GLOBAL: Applies to all requests across the system
	// - USER: Applies to requests for a specific user
	//
	// Policies are evaluated in hierarchical order: Global -> User
	PolicyType PolicyPolicyType `json:"policy_type"`

	// Priority Priority value for policy evaluation order. Lower numbers have
	// higher priority and are evaluated first.
	//
	// Valid range: 1-1000
	// - 1-100: Critical/system policies
	// - 101-500: Standard policies
	// - 501-1000: Low-priority policies
	Priority *int32 `json:"priority,omitempty"`

	// RegoCode The OPA Rego policy code. This code is executed when the policy
	// is evaluated. Must be valid Rego syntax.
	//
	// The code should define a package and decision rules. Common patterns:
	// - Define a default allow/deny
	// - Implement conditional logic based on input
	// - Reference data from the policy engine
	//
	// The Rego code is validated on create and update operations.
	RegoCode string `json:"rego_code"`

	// UpdateTime Timestamp when the policy was last updated. This field is output-only
	// and automatically updated by the server on any modification.
	//
	// Uses ISO 8601 format with timezone per AEP-140.
	UpdateTime *time.Time `json:"update_time,omitempty"`
}

// PolicyPolicyType Scope of the policy application. This field is immutable after creation.
//
// - GLOBAL: Applies to all requests across the system
// - USER: Applies to requests for a specific user
//
// Policies are evaluated in hierarchical order: Global -> User
type PolicyPolicyType string

// PolicyIdPath defines model for PolicyIdPath.
type PolicyIdPath = string

// AlreadyExists Error response following RFC 7807 Problem Details and AEP-193.
//
// Provides structured error information for API failures.
type AlreadyExists = Error

// BadRequest Error response following RFC 7807 Problem Details and AEP-193.
//
// Provides structured error information for API failures.
type BadRequest = Error

// Forbidden Error response following RFC 7807 Problem Details and AEP-193.
//
// Provides structured error information for API failures.
type Forbidden = Error

// InternalServerError Error response following RFC 7807 Problem Details and AEP-193.
//
// Provides structured error information for API failures.
type InternalServerError = Error

// NotFound Error response following RFC 7807 Problem Details and AEP-193.
//
// Provides structured error information for API failures.
type NotFound = Error

// Unauthorized Error response following RFC 7807 Problem Details and AEP-193.
//
// Provides structured error information for API failures.
type Unauthorized = Error

// ValidationError Error response following RFC 7807 Problem Details and AEP-193.
//
// Provides structured error information for API failures.
type ValidationError = Error

// ListPoliciesParams defines parameters for ListPolicies.
type ListPoliciesParams struct {
	// PageToken Token for retrieving the next page of results. Leave empty for
	// the first page. Use the `next_page_token` from the previous
	// response to get the next page.
	PageToken *string `form:"page_token,omitempty" json:"page_token,omitempty"`

	// MaxPageSize Maximum number of policies to return per page. Server may return
	// fewer results. If unspecified, defaults to 50. Maximum value is 1000.
	MaxPageSize *int32 `form:"max_page_size,omitempty" json:"max_page_size,omitempty"`

	// Filter Filter expression to apply to the list. Supports filtering by:
	// - `policy_type`: GLOBAL or USER
	// - `enabled`: true or false
	//
	// Examples:
	// - `policy_type='GLOBAL'`
	// - `enabled=true`
	// - `policy_type='GLOBAL' AND enabled=true`
	Filter *string `form:"filter,omitempty" json:"filter,omitempty"`

	// OrderBy Comma-separated list of fields to order by. Each field can be
	// followed by 'asc' or 'desc'. Defaults to 'priority asc'.
	//
	// Supported fields:
	// - priority
	// - display_name
	// - create_time
	//
	// Examples:
	// - `priority asc`
	// - `display_name desc`
	// - `create_time desc,priority asc`
	OrderBy *string `form:"order_by,omitempty" json:"order_by,omitempty"`
}

// CreatePolicyParams defines parameters for CreatePolicy.
type CreatePolicyParams struct {
	// Id Optional client-specified ID for the policy. If not provided, the
	// server will generate a UUID.
	//
	// Requirements (per AEP-122):
	// - 1-63 characters long
	// - Start with lowercase letter
	// - Contain only lowercase letters, numbers, and hyphens
	// - End with letter or number
	Id *string `form:"id,omitempty" json:"id,omitempty"`
}

// CreatePolicyJSONRequestBody defines body for CreatePolicy for application/json ContentType.
type CreatePolicyJSONRequestBody = Policy

// ApplyPolicyJSONRequestBody defines body for ApplyPolicy for application/json ContentType.
type ApplyPolicyJSONRequestBody = Policy

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Health check
	// (GET /health)
	GetHealth(w http.ResponseWriter, r *http.Request)
	// List policies
	// (GET /policies)
	ListPolicies(w http.ResponseWriter, r *http.Request, params ListPoliciesParams)
	// Create a new policy
	// (POST /policies)
	CreatePolicy(w http.ResponseWriter, r *http.Request, params CreatePolicyParams)
	// Delete a policy
	// (DELETE /policies/{policyId})
	DeletePolicy(w http.ResponseWriter, r *http.Request, policyId PolicyIdPath)
	// Get a policy
	// (GET /policies/{policyId})
	GetPolicy(w http.ResponseWriter, r *http.Request, policyId PolicyIdPath)
	// Update a policy
	// (PUT /policies/{policyId})
	ApplyPolicy(w http.ResponseWriter, r *http.Request, policyId PolicyIdPath)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Health check
// (GET /health)
func (_ Unimplemented) GetHealth(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List policies
// (GET /policies)
func (_ Unimplemented) ListPolicies(w http.ResponseWriter, r *http.Request, params ListPoliciesParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create a new policy
// (POST /policies)
func (_ Unimplemented) CreatePolicy(w http.ResponseWriter, r *http.Request, params CreatePolicyParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete a policy
// (DELETE /policies/{policyId})
func (_ Unimplemented) DeletePolicy(w http.ResponseWriter, r *http.Request, policyId PolicyIdPath) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get a policy
// (GET /policies/{policyId})
func (_ Unimplemented) GetPolicy(w http.ResponseWriter, r *http.Request, policyId PolicyIdPath) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update a policy
// (PUT /policies/{policyId})
func (_ Unimplemented) ApplyPolicy(w http.ResponseWriter, r *http.Request, policyId PolicyIdPath) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListPolicies operation middleware
func (siw *ServerInterfaceWrapper) ListPolicies(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListPoliciesParams

	// ------------- Optional query parameter "page_token" -------------

	err = runtime.BindQueryParameter("form", true, false, "page_token", r.URL.Query(), &params.PageToken)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page_token", Err: err})
		return
	}

	// ------------- Optional query parameter "max_page_size" -------------

	err = runtime.BindQueryParameter("form", true, false, "max_page_size", r.URL.Query(), &params.MaxPageSize)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "max_page_size", Err: err})
		return
	}

	// ------------- Optional query parameter "filter" -------------

	err = runtime.BindQueryParameter("form", true, false, "filter", r.URL.Query(), &params.Filter)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "filter", Err: err})
		return
	}

	// ------------- Optional query parameter "order_by" -------------

	err = runtime.BindQueryParameter("form", true, false, "order_by", r.URL.Query(), &params.OrderBy)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "order_by", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListPolicies(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreatePolicy operation middleware
func (siw *ServerInterfaceWrapper) CreatePolicy(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params CreatePolicyParams

	// ------------- Optional query parameter "id" -------------

	err = runtime.BindQueryParameter("form", true, false, "id", r.URL.Query(), &params.Id)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreatePolicy(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeletePolicy operation middleware
func (siw *ServerInterfaceWrapper) DeletePolicy(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "policyId" -------------
	var policyId PolicyIdPath

	err = runtime.BindStyledParameterWithOptions("simple", "policyId", chi.URLParam(r, "policyId"), &policyId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "policyId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeletePolicy(w, r, policyId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetPolicy operation middleware
func (siw *ServerInterfaceWrapper) GetPolicy(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "policyId" -------------
	var policyId PolicyIdPath

	err = runtime.BindStyledParameterWithOptions("simple", "policyId", chi.URLParam(r, "policyId"), &policyId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "policyId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetPolicy(w, r, policyId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ApplyPolicy operation middleware
func (siw *ServerInterfaceWrapper) ApplyPolicy(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "policyId" -------------
	var policyId PolicyIdPath

	err = runtime.BindStyledParameterWithOptions("simple", "policyId", chi.URLParam(r, "policyId"), &policyId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "policyId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ApplyPolicy(w, r, policyId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/health", wrapper.GetHealth)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/policies", wrapper.ListPolicies)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/policies", wrapper.CreatePolicy)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/policies/{policyId}", wrapper.DeletePolicy)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/policies/{policyId}", wrapper.GetPolicy)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/policies/{policyId}", wrapper.ApplyPolicy)
	})

	return r
}

type AlreadyExistsJSONResponse Error

type BadRequestJSONResponse Error

type ForbiddenJSONResponse Error

type InternalServerErrorJSONResponse Error

type NotFoundJSONResponse Error

type UnauthorizedJSONResponse Error

type ValidationErrorJSONResponse Error

type GetHealthRequestObject struct {
}

type GetHealthResponseObject interface {
	VisitGetHealthResponse(w http.ResponseWriter) error
}

type GetHealth200JSONResponse Health

func (response GetHealth200JSONResponse) VisitGetHealthResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ListPoliciesRequestObject struct {
	Params ListPoliciesParams
}

type ListPoliciesResponseObject interface {
	VisitListPoliciesResponse(w http.ResponseWriter) error
}

type ListPolicies200JSONResponse ListPoliciesResponse

func (response ListPolicies200JSONResponse) VisitListPoliciesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ListPolicies400JSONResponse struct{ BadRequestJSONResponse }

func (response ListPolicies400JSONResponse) VisitListPoliciesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type ListPolicies401JSONResponse struct{ UnauthorizedJSONResponse }

func (response ListPolicies401JSONResponse) VisitListPoliciesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type ListPolicies403JSONResponse struct{ ForbiddenJSONResponse }

func (response ListPolicies403JSONResponse) VisitListPoliciesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type ListPolicies500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response ListPolicies500JSONResponse) VisitListPoliciesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type CreatePolicyRequestObject struct {
	Params CreatePolicyParams
	Body   *CreatePolicyJSONRequestBody
}

type CreatePolicyResponseObject interface {
	VisitCreatePolicyResponse(w http.ResponseWriter) error
}

type CreatePolicy201ResponseHeaders struct {
	Location string
}

type CreatePolicy201JSONResponse struct {
	Body    Policy
	Headers CreatePolicy201ResponseHeaders
}

func (response CreatePolicy201JSONResponse) VisitCreatePolicyResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("Location", fmt.Sprint(response.Headers.Location))
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response.Body)
}

type CreatePolicy400JSONResponse struct{ BadRequestJSONResponse }

func (response CreatePolicy400JSONResponse) VisitCreatePolicyResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type CreatePolicy401JSONResponse struct{ UnauthorizedJSONResponse }

func (response CreatePolicy401JSONResponse) VisitCreatePolicyResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type CreatePolicy403JSONResponse struct{ ForbiddenJSONResponse }

func (response CreatePolicy403JSONResponse) VisitCreatePolicyResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type CreatePolicy409JSONResponse struct{ AlreadyExistsJSONResponse }

func (response CreatePolicy409JSONResponse) VisitCreatePolicyResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type CreatePolicy422JSONResponse struct{ ValidationErrorJSONResponse }

func (response CreatePolicy422JSONResponse) VisitCreatePolicyResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(422)

	return json.NewEncoder(w).Encode(response)
}

type CreatePolicy500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response CreatePolicy500JSONResponse) VisitCreatePolicyResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type DeletePolicyRequestObject struct {
	PolicyId PolicyIdPath `json:"policyId"`
}

type DeletePolicyResponseObject interface {
	VisitDeletePolicyResponse(w http.ResponseWriter) error
}

type DeletePolicy204Response struct {
}

func (response DeletePolicy204Response) VisitDeletePolicyResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeletePolicy401JSONResponse struct{ UnauthorizedJSONResponse }

func (response DeletePolicy401JSONResponse) VisitDeletePolicyResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type DeletePolicy403JSONResponse struct{ ForbiddenJSONResponse }

func (response DeletePolicy403JSONResponse) VisitDeletePolicyResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type DeletePolicy404JSONResponse struct{ NotFoundJSONResponse }

func (response DeletePolicy404JSONResponse) VisitDeletePolicyResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type DeletePolicy500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response DeletePolicy500JSONResponse) VisitDeletePolicyResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetPolicyRequestObject struct {
	PolicyId PolicyIdPath `json:"policyId"`
}

type GetPolicyResponseObject interface {
	VisitGetPolicyResponse(w http.ResponseWriter) error
}

type GetPolicy200JSONResponse Policy

func (response GetPolicy200JSONResponse) VisitGetPolicyResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetPolicy401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetPolicy401JSONResponse) VisitGetPolicyResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type GetPolicy403JSONResponse struct{ ForbiddenJSONResponse }

func (response GetPolicy403JSONResponse) VisitGetPolicyResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type GetPolicy404JSONResponse struct{ NotFoundJSONResponse }

func (response GetPolicy404JSONResponse) VisitGetPolicyResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetPolicy500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response GetPolicy500JSONResponse) VisitGetPolicyResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type ApplyPolicyRequestObject struct {
	PolicyId PolicyIdPath `json:"policyId"`
	Body     *ApplyPolicyJSONRequestBody
}

type ApplyPolicyResponseObject interface {
	VisitApplyPolicyResponse(w http.ResponseWriter) error
}

type ApplyPolicy200JSONResponse Policy

func (response ApplyPolicy200JSONResponse) VisitApplyPolicyResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ApplyPolicy400JSONResponse struct{ BadRequestJSONResponse }

func (response ApplyPolicy400JSONResponse) VisitApplyPolicyResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type ApplyPolicy401JSONResponse struct{ UnauthorizedJSONResponse }

func (response ApplyPolicy401JSONResponse) VisitApplyPolicyResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type ApplyPolicy403JSONResponse struct{ ForbiddenJSONResponse }

func (response ApplyPolicy403JSONResponse) VisitApplyPolicyResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type ApplyPolicy404JSONResponse struct{ NotFoundJSONResponse }

func (response ApplyPolicy404JSONResponse) VisitApplyPolicyResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type ApplyPolicy500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response ApplyPolicy500JSONResponse) VisitApplyPolicyResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Health check
	// (GET /health)
	GetHealth(ctx context.Context, request GetHealthRequestObject) (GetHealthResponseObject, error)
	// List policies
	// (GET /policies)
	ListPolicies(ctx context.Context, request ListPoliciesRequestObject) (ListPoliciesResponseObject, error)
	// Create a new policy
	// (POST /policies)
	CreatePolicy(ctx context.Context, request CreatePolicyRequestObject) (CreatePolicyResponseObject, error)
	// Delete a policy
	// (DELETE /policies/{policyId})
	DeletePolicy(ctx context.Context, request DeletePolicyRequestObject) (DeletePolicyResponseObject, error)
	// Get a policy
	// (GET /policies/{policyId})
	GetPolicy(ctx context.Context, request GetPolicyRequestObject) (GetPolicyResponseObject, error)
	// Update a policy
	// (PUT /policies/{policyId})
	ApplyPolicy(ctx context.Context, request ApplyPolicyRequestObject) (ApplyPolicyResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// GetHealth operation middleware
func (sh *strictHandler) GetHealth(w http.ResponseWriter, r *http.Request) {
	var request GetHealthRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetHealth(ctx, request.(GetHealthRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetHealth")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetHealthResponseObject); ok {
		if err := validResponse.VisitGetHealthResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListPolicies operation middleware
func (sh *strictHandler) ListPolicies(w http.ResponseWriter, r *http.Request, params ListPoliciesParams) {
	var request ListPoliciesRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListPolicies(ctx, request.(ListPoliciesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListPolicies")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListPoliciesResponseObject); ok {
		if err := validResponse.VisitListPoliciesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreatePolicy operation middleware
func (sh *strictHandler) CreatePolicy(w http.ResponseWriter, r *http.Request, params CreatePolicyParams) {
	var request CreatePolicyRequestObject

	request.Params = params

	var body CreatePolicyJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreatePolicy(ctx, request.(CreatePolicyRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreatePolicy")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreatePolicyResponseObject); ok {
		if err := validResponse.VisitCreatePolicyResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeletePolicy operation middleware
func (sh *strictHandler) DeletePolicy(w http.ResponseWriter, r *http.Request, policyId PolicyIdPath) {
	var request DeletePolicyRequestObject

	request.PolicyId = policyId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeletePolicy(ctx, request.(DeletePolicyRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeletePolicy")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeletePolicyResponseObject); ok {
		if err := validResponse.VisitDeletePolicyResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetPolicy operation middleware
func (sh *strictHandler) GetPolicy(w http.ResponseWriter, r *http.Request, policyId PolicyIdPath) {
	var request GetPolicyRequestObject

	request.PolicyId = policyId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetPolicy(ctx, request.(GetPolicyRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetPolicy")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetPolicyResponseObject); ok {
		if err := validResponse.VisitGetPolicyResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ApplyPolicy operation middleware
func (sh *strictHandler) ApplyPolicy(w http.ResponseWriter, r *http.Request, policyId PolicyIdPath) {
	var request ApplyPolicyRequestObject

	request.PolicyId = policyId

	var body ApplyPolicyJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ApplyPolicy(ctx, request.(ApplyPolicyRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ApplyPolicy")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ApplyPolicyResponseObject); ok {
		if err := validResponse.VisitApplyPolicyResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}
