// Package engine provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package engine

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/7RXbW/bNhD+KwS3Dyug1knTFai/uYmKamgTz3EKFFsQ0OLJYiGR2pFy4wX67wNJvVtJ",
	"tjT7ZIvk3T333AuPdzRWeaEkSKPp/I4i6EJJDe7jPeMr+KsEbexXrKQB6f6yoshEzIxQcvZNK2nX4Jbl",
	"RQb2LwfDREbnNJI7lglO0GshBUOWgwHUNKDaMFNqOn9zdBRQI4yVHUvQgJp9YTfeL85uVuHvV+HlmlYB",
	"1XEKObPGfkZI6Jz+NOscmfldPQsRFdKqqgLKQccoCgt5wkwV0A8KN4JzkE/09asqCVdEKkNStgOiyyQR",
	"sQBpSAGYC62FkpoYZT8ThTkxqdBEFYBO+YCRk46RZStMOEgBvONkGa4+R5eX0cX5zVl4HoVnz8DMOgXC",
	"SpOCNNZr4KTUgIQr0J1vnUMP+FMFNJIGULLsEnAH6G0+zu4Px9YbJdpZJeAPBnSpMhHvT5VMMhE/NaU/",
	"qe+ALwsUCoXZk8LpJAYFcMuF2gGi4EBSsU0PDw6C/K4XZK8mbrB1Ib74FJ1+vTm9OP/wKTp9jtQfmSIb",
	"MN8BJMmGjjHJp30QoC2KFXyD2AB/Io01Cri1x4XJ9gRrhcSk0Cv/jq63B3Q1Ih1dq/C38HT9LIUwsjGA",
	"VQX0StoqUSj+fjIHX1wL6hWbracYgdtPlmnC0JsU6JOLxTFo7esMQasSYxhQdNxRtBiqbdR0VF2dL67W",
	"H8PzdXS6eB7GRiYdyBr8pjTkO/MdpEC1Exw4UWjPCN+KadUCcHdP2ywKtC3FCH8lNeTdjWyfuXXgvtpJ",
	"DlqzLXTeaoNCbq2TQmrDZAyHOuq7jggXgEQA0oDazsYMndMSxUuEBBBkPKm4CcNY7cf1ekn8JokVh75S",
	"Ic3J606ZkAa24JpVHcexsstUoamd1GWeM9xPYfELY2HHKbF7T/OxCmibR/M//G7rdwP5uhVTG1s6Fk64",
	"Y1nJDPSmiWFYbasWMdz0g/NQDl7681FzfAztQN/DqPzMcwgL6hP85ocBBlRD5jrJTV0AOBFdL9WUCJJG",
	"hmx63fc/5N5iuVxdfAnPyEvSZHcp45TJ7VDnn/LzxVn0IRqctAWbK26zZHSYBhRkmVumGws0oI2KHtn3",
	"ZM4DvE7x1Po3FcUx04e5VUDs2jLnwtLCsmVv32AJwT1hsJIiafrZL0kGt2KTAfFBfkEP0Iyz0Fo+xFy5",
	"LpSo5tpgbhi5f45ZLCOSKGxmjZo8B8n2U7gtlPYXBEg/rukX9OCyDOVWSCBhJ71YRjSgO0DtDe6OWVak",
	"7NiyqgqQrBB0Tk9eHb06oQEtmEkdn7MmD+YwUdbK/44aT31QE0bqiJMm4u3jgG2ZXSMsy0h9hVqyG2vW",
	"P27fDrl1gxU2O1jm5hSfMYSRXsa0c2jEewBW7VxRW32v+P75RtKRlWqYEDbV3ELvifX66Oh/MF/3s4k7",
	"uhd+XbpxIikzG/A3HsiU/hbwrPcgdCLHj4sM5iQndPK4UPcWcxJvH5dox1En8O5xgdFjoAror/+GgakX",
	"jZtc6ru4S7Xeo3efKcbb/O73cbbVtlF0UaHXLmj+6WL37miJdlicsULMugq9boXvpufWXpdoS8GalCyH",
	"QR7Q6rr6JwAA//8pv7SIBhAAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
