// Package v1alpha1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package v1alpha1

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/9xbbXPbOJL+KyjOVjmpEmVKtvyiq9SVxlIS3Tq2V7bnZmeUcyCyKWFCAhwAtK2k/N+v",
	"GgDfJCb2JJ7Zrf2UWCSARqP76ae7wc9eKNJMcOBaecPPXkYlTUGDNH9diISF62l0QfUK/45AhZJlmgnu",
	"Db2rFRAJSuQyBMIi4JrFDCSJhSR6BSQzo7vkXa40WQCh5JYmLHK/k+l4zvWKahIKHguZKqIFGU0u/F6/",
	"TyT8njMJKco1nHOf9PyDPRKuqKQhSkcSwZf4+6m4AxlSBSQBjU86hOfpwvyH8ois1tkKuCKCJ2t83wij",
	"NJWa3DG9ItSNK58Bj5pPiJBuyjn3Oh7c0zRLwBt6y0QsaOLTXK98uyev4zHUTIb66nicpvhe5rTodTy3",
	"rcgbaplDx1PhClKKqk3p/SnwJer5YK/jpYwXf/Y6OJ8GiTP/36/U/xT4x+9fuP/47z8HnYPeQ/H7y//+",
	"m9fx9DrDlZWWjC+9h4cHXFplgiswBztKJNBoPblnyp57KLgGrvG/NMsSFlI85N3fFJ7052rTaAOassQb",
	"OuOwupqOyc62OnYItesQsAuhepSmPEThgvDg8CA4CPxDOD7wDwYh+HAUHPnQowdHe4t4//ho4XU8panO",
	"lTfcD447nmbaqH5WmN3WAm7no9PZZDT+583k5+nl1aX3UFf13yTE3tD7Ybcy/V37VO1OpBTSKqxp7F9a",
	"8aHj/UijGfyeg9LfqMnXDJKI7EhYiptQRLBDUrRELozbQJrpdVN1h8d7+1G8B/7+4mDP3+8fL/xFEA/8",
	"xVG0Nwgg7B0MoKG6oFLdlFsvlFZkUvP4UnvTs59Gp9PxzWj25vrd5OzqGfT3lWUfOt5rIRcsioB/owb/",
	"KXISCaOxFb0FovI4ZiEDrkkGMmVKMcENwGQgEWyIXjFFRAbSTN5U76If7kX7MPDjA3roHx0HPX8RRuDH",
	"vf7e/uDgEH9pqHevUu9FuRyJgDOIKq1eTGbvppeX0/Ozm/HkbDoZP4NaEYPR4xB8Q6ohIrkCSSIBqtJG",
	"pYKvaOCh4005ogxNLkHegrRrftt5jDjJOdxnEKJIgDMREYa5lBCRuxVLgGRShKAU40sTLJxdNA+iFx0e",
	"BcFh4B/F9NA/PIhiPz4Ojv24vzg83g/pIDgOawcxaNq53QxRZjdWiLqJX01mZ6PTZzHttpUeOt6Z0K9F",
	"zqPvA9hWYC0P2MBQU2vHi8FBHAyofxAdDfzB/iLyo0N66EdBPDjsU9g7OqQN891vAVacOzbClyo7O7+6",
	"eX1+fTZ+Tjit1nnoeNccNykk+wTfqrSfDMrUXAKtPpRg6AlNFKESCnYRoTvQEM3QekPBZpr6pD0LCD4M",
	"4gMfvd+nizDyoYYHDX32Kn2OmoKU8b9U6vXZ6Prq7eTsanoyunoWSNhY0mzLbXeRa3JHreFkUtyyCCKk",
	"N0wRZvEZ1zcqNIO/BwIKwJ/BUhC15preE8YbUS7GuNfUdR+Ojnu9w55/HNMj/+gwDvyA9qjfD4+Pg0G4",
	"OAiOo7qu+/1K15Xcm87+ejQ9nYxvLmaTk/Oz8fRqen72DIreWu+hnNNwqlJ7zWHmZ1LQMRKLJBF3CIOz",
	"1yfk8Cg4JBdSLBJIydjoUhkea4jx8V53zuf8wh6dIkrLPNS5LDGWGSZtZUIaPrqYkpiyJJeguoa+ZhIh",
	"XzPLA4vT2pTxbZ5S7iPRoYsECNxnCeV2WpVByGIWou/YEGJxnYdARGyJv5W/O+eXK5EnUWFrhIY4hZly",
	"U9IIbiFB0ZycFc3eZkePmfQ2Aa7b2OZerzn7PW9JYJiq9tqIYDyELrlWEOcJvjrnWtLwI54gHlQEi3y5",
	"ZHy5uY8nkjarFm/o5ZL5EmIwC7ZtqXCCrcO7urog9iFBhdWlMFSwXIJxvdevpmZcwxJM6HI+9YhdqDxN",
	"qVxvnDsx09W3/hTOWe3L/rB1TLMpKdVRnNa6oA/1pbvkCg+PKfMkpFxwFtJkzu0pokrc2fA89Ya/btPd",
	"Ti3WdTZziY43m1yeX89OJjeTn9+Ori8RtjutGNPxRj+ez+zz8+urm/PXN7PR2ZuJ1/Guz6bvLk4nuJx5",
	"XPIRfDT6aTQ9Hf14ii+OJ6Px6fQMFzuZTMbm5c2g0Wnhlu8bB7C9w6fa2UM9a/3Vc2frbK8wlPflMLH4",
	"DUKNx/gWaGLLBk3MyVqLCSfFMRF8XlhULSBXm1nZiVEuGp3zZF1k00/3EDMDKTexOff6UTW4oVv77nj3",
	"PoXMLwW3G0aCqHCck/19x8uSXNKkvh3kwglolNBVBxhf5gmV9ZfccpYH+inldAmyG4Vpl4ld9xYKe8qU",
	"NgSSgZq5WLOtiOIJSUEpugQDfQlTGv0qc8NNzJmigkw5xoaivT7BJVCHPKIyIinolYgahZu2iMPhXt9k",
	"dAk3Wny0+d5GRoM/GzkkaMngtnBxHElwJBqHBJUnWnXJNLYJsqnSCD3nmQQFXHdwjARD97ggqTC0zw7C",
	"/RiIMCIQkwZRjAGI38qGLJd8Z1QqjDJrEias2lNlMLD+n9tf0l8+/fLzP9j5b9d38T9evWoDtUKZ2xs2",
	"ahRxURYrLEeRlOpwtZEfkVAyDZIhgWcaUvUYe7FJRAWrHpWSrrfsuRSvzZPdHC3W45SNFIWcX4zIi/MM",
	"OHGJy2gJXL/c3JdlMG45EkHMuE1hkfY7lpwnoEhuckNDHxGyzeGElOOpqFBkEM25FiRisYEuTRJkEIq8",
	"eHN6/uPoFO3h+nIye4nRANbGDoxCISJ0SZEOzLlTarFWQheAWVwCoRbS8i64pUluEmvGSSaZkMwYWwSy",
	"zbxDCVTDjWZpi7ddsRSUpmlG7lbAazVSw2Ds0MhFL8ONjWnmOsu1b+uXKBHNtUDiFNIkWRMFGq0T57Lp",
	"p9HvtQJFppfn5Ogg6BEL9bZSh5J9EtwUBawn7webNt0P+gd+0POD46teMNwLhkHwSz1iRFSDb7b4BAxu",
	"qGBTI+fmPzQhlogC0qfyeUkrbM6rSJbLTChrCQtY0VsmcLuXeZYJqdFh5MdI3HG3Yd1CwiZIO9G5aGti",
	"ZgGOhlIoRWhiU3qG7zNe8IwoDy3n57dMCo5DvE69ftsP9o/aFMFUltD1ja0KP8Ks8KWtQnpJa9ZZcfor",
	"3C7jc27KPkjgZEzN/iooW0Cl1VvY1MgbU10gG1njRVHPru9rMNgsTG9tEgy7j+z+YponujCM5nb/dwWI",
	"z3UfYIpYeq2TtckUbqFLxkyZCctg5ABdz3nlmVEuDftugEgEITNVv40NN8x0IUQC1BS/WPT01GDjSNp8",
	"FQ9gzlma5tocKI01SOvjTHADSmQ6LgBNOD/AI7U5B0TkltE5/z0Hua4IM7HVDDPJfxEWN/KeTg0GyBI4",
	"SKpRY+T6ejo2uPDaJJuq1mZxZRgURfBb3Oe2yto7Hc/bsXgURww43xTgbCoRUcSs2i4aGPx1CPL+Dmsf",
	"TQeDO5OI/bYQZKKDzfucRbo4QRgPRYoWVsSLLvKHuuFWtmjOnsUGPIzIqpy4FsQF13Cvu3M+xRPcCDw4",
	"YfNI2xZCS8RFajLN+YlIU8HdfB9hbXtnNaQa1hCsg+QNM9VOkX3jGzgAweSGRUNbTK7MH585RBwW/zFQ",
	"hQ8kLJngQ7IEsZQ0Wxkyb3/Ex5qBrAbhX+QFkhl8rVPSyA4BHXZfNu3vs1fH2qFXbcEYztKea658oEr7",
	"PZOVALLmYv4a/alYTXseUhYmTRriUN8F0HlJk3Y/F029h7nXdWzySzDwhRj9RV80K3/FG0shWt2y5nnl",
	"i8/kgnaNm/b8/BI5WTNkk1qtcBMqv4iMc2MtlsQNyQhnANO5qRt7EaKNStdKQ4qDkO81hpSvG2epyjlo",
	"1g0aikGlwfRWDCSVoTViw/aGxEVKf54HwR6Qa1V0hF0ZwcqM6fnlZNbMv8tH2zp1lLIRMU0jo6nei4J6",
	"WujCDTklO7kNYTK01PbEiza4aQHN+YotMd6WDNYwycauYyaVNuq3NXRJ+RKGpOf3giCwLfheEAzJiXOq",
	"Xav4MjKbV4KeP8CXLou0sP50ENjJhiihX4pSvVI3815rpSql9yxFdeM8Jui4P9uKWGXJsP3uAiYsJr1w",
	"ijSFIWumJuFAuL2HMNemZ9Ug7HNex+LqisNWydvlmmBndISsSHpIRsOPmNDauqHlKzb76RIH5UXxwAD5",
	"uBjoLAV9QtztRsDN3YYyR0f0KGIjScSShWRBlYlOhPEsNyA/K4tpEdWUxFKkdd8FvmQcCvGrNIwpu0sX",
	"7VzaYraQZ/hr1VPcRq5iv7lefcKpG/sgr0hME2XWtD98nnNiBe6iy3abnc5XrwgC1cY7UiSAj+YejVLG",
	"596cPxgx6nxlMNg7eJTL2u18Uy6XUKWdOv5oQudGNQMGKpryNUlFhABWIeXzJXqD4f7gOxK9jXpCI9lp",
	"Ro66X/7h+tlmAL5h0UOjmlYWMhrlszI6frV85t56ML0exmNRtL5oqL3h5+1O2+TCD0WaJYxyTWaTyyvb",
	"cBGSmJmRMn61KsKqxHJ88q54452TqixT2UktW8B38e8JX1EeWm9H+isUTRR5MZpcvNysySnbpShU6gvJ",
	"gGuba7Ml7ziyidKezK7HNf81W7nYqEsZuX74gfwd1uQ1UJ1Li+6v8yRpncD5hVV2QTFd0m5esKU1v8p8",
	"LGlCw/eLNCYi07FdJoF7hrwhZokGWbRdMlS3WbSUpSRUErKEOl1Z9zIzNY/PNgdWlEcJ40vjKAkLwZVN",
	"3VWuUUbDFZB+N/A6Xi5N+VbrTA13d+/u7rrUPO4Kudx1Y9Xu6fRkcnY58fvdoLvSaVLrrnjNA8dz9Tre",
	"LUhl7eu2R5NsRXs4RGTAaca8obfXDbp7luitTL5TlH2Hn70l6C9Wu8MVhB+NvrdtzS1dHtw0QtIC+m1V",
	"aq/dHusHwROawk/rrr4tStZb3nXpUgWmSFGVNw1W23Pa2Jd5tFsvsraq4pQhGyx9zwClqlliZUWdyr7s",
	"RULDrWxFyZj/6+KxAWHjlx/skA+1dN2scDI59ZVe20aqBHsZyQT0DzVgfLVjWeLOB/PEVVJeIdp+2H4X",
	"OeYOGZ2NycaLRrhzJ2xNNiP/zWJdk86JUFJCFX4gL1xIftl8hmq0UtSR3Qwxv9bqnsW7W/ZUb0kY+62u",
	"mv76nV2AU6C37qaca8li1oaE1rxr2rVWDRv9hw813iPhlolcGaS0XREtyBJ0c90nNgDMPVBTvKldBK3a",
	"HvXLB1uRdFMZ7yzpdYy+7BWUSY7OJTdh3u7VXt8iKV27Z3MeA2YE9aZJzku47RR00kw3CLqkWNDmGkwR",
	"ZNvdFn7etsuU3lsFK/YJGhut5TffR+23VWS9seZfJmPMsmRt7ymA6Wp1SVkrrqLHYr3lih+GpNlFqHvk",
	"h6GhnfiopKsTq5XvdWr3bptbb1cAHhv0BSO0G/9jBoi5CPUVoMtiKE5cy8pwWmM1Bl3IYt0lExquHNm1",
	"xc05t9zFctodqsId1N0OLrHTxZymtL2dOhbtGKR1B2byU1zMaLh4Df9fxyP8u4ZELSdTx7ptOKtQbhPP",
	"Ohsjm8dRe/YFrRfo2+4PmzNsHsj7PzEAtzaKW8Jxo02JCP7Q8fatHG3Tl/Lu1q5HmyG9x4c07gGaQXuP",
	"D6ruED90vMFTJGu779qkGGbTtZRC06VJQ8ow9t6UxVQL1TgxFqQIJRzutpqgpv6PCZ8D6q0GwJrQOXfE",
	"mCrk6YYCk1tGbSBj0Qey0RwwwL7VEJhzl0PesSQp2wJVV2ArTlvJL6qC4lfidNnA2+Lw0/FWs+RbpJvz",
	"Wb0196LMZvv9l1/9MOSy+sYj2fhGBB+fYFrHuK3XJ0/7iATHTYrPQ77545ANZGCR963fgfzBj0De2xQd",
	"lP5RROtnA5CLMmve/L7lYQu2en/KqhuVUlfNs+10onJzwTfOkwS1vgIaua+bToVduf2umatkF9PUbiJV",
	"AtbuDbkskGas637thiLdve3tfr1cX7+G1fbhzr81yu4Hx4+PaH5rhKP6/cdHbV5Cfj5MP3EFyxoutyN7",
	"PaOsNXysuSSgW6qCY/M7gn6jQVziq+t8QMSKmmlIubtqlPNIcHCQh7RdkX6wT86EwSrgmghes2ZiZCh7",
	"ydUSDl7VnCstBV+SUHDFlAYerolPEELSzFzwMskDjRo37SrxkrVtzcx5sZLFaJdv7BvZNDFfOLSFEauL",
	"L4WRtlOsXtltfHnYwn/2t3Xv/N4eTdPvyQsuiIOdl3+pf+w/PqL8SuT5TNyqvrTCLxGX1hLJzObbxojt",
	"jcSCvCzWhGlFXFg2hu0u/bHNy4E98ga27ga2Gckb0H+ShQR/XahxJYrNYPOfb2d4yI8ZWZa3GNm1rcIS",
	"yu0HTOV107W7ihd/qYD7uO3tEzv7pvl1zLcCuQJFLq6v5pxxpRH9REwuRlcnbw1d/fq6P/xgK8uz6vc5",
	"HyUJKXrZLiFOXTuw/MbGFfkd/bKIXeO9c+5WMm8B10zWENm2c1a16SKqaSHQtGykmw8llO3XVV+VOJFq",
	"ccY2mGwiTfUK/2WR+asqK5AX1YBwRfkSoo1G/cutZNsntY5Zi6+PsixZP5+3/2uZ7F8IL0VHcBtc/n15",
	"4b8Gj5zjfx2SzBAzhbU828ZB5r5bNVzel0O3M95Gc6vR6KtVClx2V6778P7h/wMAAP//3qz/bmxBAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
