name: E2E Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  e2e:
    uses: dcm-project/shared-workflows/.github/workflows/black-box.yaml@main
    with:
      up-target: e2e-up
      test-target: test-e2e
      down-target: e2e-down
      images: "quay.io/sclorg/postgresql-16-c9s:latest docker.io/openpolicyagent/opa:latest-static"
